# http://wiki.ros.org/costmap_2d

# footprint: [[-0.85, -0.45], [-0.85, 0.45], [0.85, 0.45], [0.85, -0.45]]
footprint: [[-1.05, -0.6], [-1.05, 0.6], [1.05, 0.6], [1.05, -0.6]]

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

max_obstacle_height: 0.2
obstacle_range: 4.0
raytrace_range: 4.5

# -- layer definitions

# http://wiki.ros.org/costmap_2d/hydro/staticmap

static:
  map_topic: /map
  subscribe_to_updates: true

# http://wiki.ros.org/costmap_2d/hydro/obstacles

obstacles_laser:
  observation_sources: laser
  laser:
    data_type: LaserScan
    clearing: true
    marking: true
    topic: scan_merged
    inf_is_valid: true

# http://wiki.ros.org/costmap_2d/hydro/inflation

inflation:
  inflation_radius: 1.0
  cost_scaling_factor: 10.0
