# http://wiki.ros.org/costmap_2d

# footprint: [[-0.85, -0.45], [-0.85, 0.45], [0.85, 0.45], [0.85, -0.45]]
footprint: [[-0.9, -0.5], [-0.9, 0.5], [0.9, 0.5], [0.9, -0.5]]

# global_frame: car1/odom
# robot_base_frame: car1/center_big_car
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

# max_obstacle_height: 0.2
obstacle_range: 4.0
raytrace_range: 4.5

# -- layer definitions

# http://wiki.ros.org/costmap_2d/hydro/staticmap

static:
  map_topic: /car1/map
  subscribe_to_updates: true

# http://wiki.ros.org/costmap_2d/hydro/obstacles

obstacles_laser:
  observation_sources: laser
  laser:
    data_type: LaserScan
    clearing: true
    marking: true
    topic: /car1/scan_merged
    inf_is_valid: true
    min_obstacle_height: -1.0
    max_obstacle_height: 2.0
    
# http://wiki.ros.org/costmap_2d/hydro/inflation

inflation:
  inflation_radius: 1.0
  cost_scaling_factor: 10.0
