# http://wiki.ros.org/costmap_2d

global_frame: map
robot_base_frame: base_link

rolling_window: true
track_unknown_space: true
width: 100
height: 100
transform_tolerance: 0.5

plugins:
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}